### ISSUE TITLE
Backend Broken after first installation

### ISSUE THREAD

**Issue by frostblogNet** [netresearch/dhl-module-shipping-core#3] opened 2020-07-15 09:10 UTC
Magento 2.3.4-p2 Commece
Dhl_ShippingCore: 0.1.0

After a fresh installation of your dhl extension when I go to the admin backend and then to configuration -> sales -> DHL Shippment 

I`m getting the following error

![grafik](https://user-images.githubusercontent.com/19548641/87526853-9faeac80-c68b-11ea-8f3e-b5c0c40709ba.png)

The reason is that the config value is not in the database and therefore the scopeConfig->getValue will return null which is of cource not a string.

**Comment by mam08ixo** [comment] 2020-07-15 09:20
There is no version 0.1.0 of this module.

In Magento, config values are not only retrieved from the database. If the value is not available there, Magento attempts to read from [config defaults](https://github.com/netresearch/dhl-module-shipping-core/blob/1.0.1/etc/config.xml#L5).

Find out why that does not work on your instance. Clear cache etc. Check if there is something in `app/etc/config.php` or `app/etc/env.php` that is blocking the config defaults from being applied.

**Comment by frostblogNet** [comment] 2020-07-15 09:32
Thanks for your quick response. Version 0.1.0 is the version mentioned in etc/modules.xml 

here are the composer versions:

dhl/module-carrier-paket                                          1.1.0                                        Carrier implementation for DHL Business Customer Shipping
dhl/module-carrier-paket-returns                                  1.0.1                                        Carrier implementation for DHL Business Customer Shipping Returns
dhl/module-shipping-core                                          1.0.1                                        DHL component providing utilities and frameworks for advanced shipping features
dhl/module-ui                                                     1.1.0                                        Module providing the UI integration for the DHL global webservices components
dhl/module-unified-tracking                                       1.0.0                                        Integrate the DPDHL Group tracking web service into Magento® 2 carrier modules.
dhl/sdk-api-bcs                                                   1.0.0                                        DHL business customer shipping API
dhl/sdk-api-bcs-returns                                           2.0.0                                        DHL Paket Retoure API SDK
dhl/sdk-api-parcel-management                                     2.0.0                                        DHL Paket Parcel Management API SDK
dhl/sdk-api-unified-location-finder                               2.0.0                                        DPDHL Group Unified Location Finder API SDK
dhl/sdk-api-unified-tracking                                      2.0.0                                        DPDHL Group unified shipment tracking API SDK
dhl/shipping-m2                                                   1.1.0                                        DHL multi-division shipping extension for Magento 2

I know that it will use config.xml but it does not and because you type cast the retrun value of getModuleVersion it failes. You can easly fix this or find out why it is not falling back to config.xml

**Comment by moehrenzahn** [comment] 2020-07-15 09:37
Hi Jens,

unfortunately we cannot fix the issue since we cannot reproduce the issue you are having. Under normal circumstances, the retrieval of a configuration value from config.xml never fails. If you can provide us with more detailed steps of what exactly you did we can look into it further.

Also, please note that the `setup_version` value is not the version of the module, but only the version of the database schema, which is a separate thing.

**Comment by ngolatka** [comment] 2020-08-24 09:27
Closing this because there were no further questions.

**Closed by ngolatka** 2020-08-24 09:27 UTC
